global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jmeter'
    static_configs:
      - targets: ['jmeter:9270']
  - job_name: 'mynode'
    static_configs:
      - targets: ['host.docker.internal:9182']